version: '3'
services:
  mysql57:
    image: mysql:8.0.29
    restart: unless-stopped
    container_name: db
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: market_management
    volumes:
      - .db:/var/lib/mysql
  web:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development